CREATE TABLE chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_company_id uuid NOT NULL REFERENCES client_companies(id),
  thread_id uuid NOT NULL,
  role text NOT NULL CHECK (role IN ('user','assistant')),
  content text NOT NULL,
  citations jsonb NOT NULL DEFAULT '[]'::jsonb,
  author text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  seq bigint GENERATED BY DEFAULT AS IDENTITY
);
CREATE INDEX chat_messages_thread_idx ON chat_messages(client_company_id, thread_id, seq);

ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages FORCE ROW LEVEL SECURITY;
CREATE POLICY chat_messages_tenant ON chat_messages
  USING (client_company_id = current_setting('app.current_client_id', true)::uuid)
  WITH CHECK (client_company_id = current_setting('app.current_client_id', true)::uuid);

GRANT SELECT, INSERT ON chat_messages TO bookkeeping_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO bookkeeping_app;
